{% set version = "2.2.3" %}
{% set sha256 = "22698d9470e70d31e33e9182ca5bcaa67b765917bbcecc233879e270d92eb510" %}

package:
  name: gridss
  version: '{{ version }}'

source:
  url: https://github.com/PapenfussLab/gridss/releases/download/v{{ version }}/gridss-{{ version }}-gridss-jar-with-dependencies.jar
  sha256: '{{ sha256 }}'

build:
  number: 0
  skip: true # [osx]

requirements:
  run:
    - openjdk >=8
    - python

test:
  commands:
    - "gridss gridss.CallVariants --help 2>&1 | grep 'USAGE: CallVariants'"

about:
  home: https://github.com/PapenfussLab/gridss
  license: GPL-3.0
  license_family: GPL
  summary: 'GRIDSS: a Genomic Rearrangement IDentification Software Suite'

extra:
  identifiers:
    - biotools:gridss
    - doi:10.1101/110387
