{% set version = "0.5" %}

package:
  name: genrich
  version: "{{ version }}"

source:
  url: "https://github.com/jsh58/Genrich/archive/v{{ version }}.tar.gz"
  sha256: 88491354ad1149847ef80bfedf06478087142ac3d0f7b72ebd9779c455afb87a

build:
  number: 0

test:
  commands:
    - Genrich --version

about:
  home: https://github.com/jsh58/Genrich
  license: MIT
  summary: Detecting sites of genomic enrichment.

extra:
  recipe-maintainers:
    - mjsteinbaugh
