package:
  name: minepy
  version: "1.2.4"

source:
  url: https://files.pythonhosted.org/packages/90/a6/cdfe0f50b16d18196b3a21d3df8c06c361ccbd553717093133a88227823b/minepy-1.2.4.tar.gz
  sha256: 04d9525a353065159d6f86d6c70f33b738d437b53a41527462cbe719225c25ed

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - setuptools
    - numpy >=1.3.0

  run:
    - python
    - numpy >=1.3.0

test:
  imports:
    - minepy

about:
  home: http://minepy.readthedocs.io
  license: GNU General Public License (GPL)
  summary: 'minepy - Maximal Information-based Nonparametric Exploration'
  license_family: GPL
