{% set version = "0.5.4" %}

package:
  name: cgat-apps
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cgat/cgat-{{ version }}.tar.gz
  sha256: df54c25707ba87e42c853cd6e851ba672de1f1ffea6c122e1408229a53b007a8

build:
  skip: True # [not py3k]
  number: 1
  entry_points:
    - cgat = cgat.cgat:main

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - python
    - alignlib-lite
    - biopython
    - future
    - matplotlib
    - numpy >=1.10.*
    - pandas
    - pybedtools
    - pybigwig
    - pysam
    - python-lzo
    - pyyaml
    - quicksect
    - scipy
    - setuptools
    - six
    - sortedcontainers
    # Misc dependencies
    - bedtools
    - ucsc-bedgraphtobigwig
    - ucsc-bedtobigbed
    - ucsc-wigtobigwig
    - coreutils
    - grep
    - libpng
    - zlib
    - nomkl

  host:
    - python
    - cython 0.29.*
    - alignlib-lite
    - biopython
    - future
    - matplotlib
    - numpy >=1.10.*
    - pandas
    - pybedtools
    - pybigwig
    - pysam
    - python-lzo
    - pyyaml
    - quicksect
    - scipy
    - setuptools
    - six
    - sortedcontainers
    # Misc dependencies
    - bedtools
    - ucsc-bedgraphtobigwig
    - ucsc-bedtobigbed
    - ucsc-wigtobigwig
    - coreutils
    - grep
    - libpng
    - zlib
    - nomkl

  run:
    - python
    - cython 0.29.*
    - cgatcore
    - alignlib-lite
    - biopython
    - future
    - matplotlib
    - numpy >=1.10.*
    - pandas
    - pybedtools
    - pybigwig
    - pysam
    - python-lzo
    - pyyaml
    - quicksect
    - scipy
    - setuptools
    - six
    - sortedcontainers
    # Misc dependencies
    - bedtools
    - ucsc-bedgraphtobigwig
    - ucsc-bedtobigbed
    - ucsc-wigtobigwig
    - coreutils
    - grep
    - libpng
    - zlib
    - nomkl

test:

  imports:
    - cgat

  commands:
    - cgat --help
    - cgat --help Conversion
    - cgat gtf2table -h
    - cgat bam2bed -h

about:
  home: https://www.cgat.org/downloads/public/cgat/documentation
  license: MIT
  license_file: LICENSE
  summary: "Computational Genomics Analysis Toolkit"
