package:
  name: hichipper
  version: "0.7.5"

source:
  url: https://files.pythonhosted.org/packages/0d/5a/10d2d2da8ab9c96e67359ca14e3a88ce8cb87c48988f2a4af6b3a6cc50dc/hichipper-0.7.5.tar.gz
  sha256: 77b8423a23aa0f4c77ad4854e583adcaf2c13790be57fa36542972fd49e48dde

build:
  entry_points:
    - hichipper = hichipper.cli:main
  number: 0
  skip: True  # [py3k]

requirements:
  host:
    - python
    - setuptools
    - click
    - pyyaml
    - numpy
    - macs2
  run:
    - python
    - click
    - pyyaml
    - numpy
    - macs2

test:
  imports:
    - hichipper

  commands:
    - hichipper --help

about:
  home: https://github.com/aryeelab/hichipper
  license: BSD License
  summary: Processing HiChIP data into loops.
  license_family: BSD

