package:
  name: smeg
  version: "1.0.1"

build:
  skip: True  # [osx]
  number: 2

source:
  url: https://github.com/ohlab/SMEG/archive/1.0.1-a.tar.gz
  sha256: b4ced97b5f361a955426f3bd9a1189ee9df01f24f41d009943fc3959470c2be0

requirements:
  build:
    - {{ compiler('cxx') }} 

  run:
    - perl-file-find-rule=0.34=2
    - parallel
    - mauve
    - roary=3.12.0
    - prokka
    - subread
    - r-dplyr
    - r-ggplot2
    - r-gplots
    - r-getopt
    - r-gsubfn
    - r-wgcna
    - r-ape
    - r-dynamictreecut
    - r-data.table
    - samtools=1.8
    - bamtools
    - bowtie2
    - readline>=6.2

test:
  commands:
    - smeg -h
    - pathoscope -h

about:
  home: https://github.com/ohlab/SMEG
  license: MIT
  summary: Strain-level MEtagenomic Growth estimation (SMEG) measures growth rates of microbial strains from complex metagenomic dataset at low coverage (1X)

