{% set name = "schema-salad" %}
{% set version = "3.0.20181129082112" %}
{% set sha256 = "274d7dcc09f4d9fa364ac6f002e614354f4b554a4ca3a7c3dfa3002cd006e7f5" %}

package:
  name: {{ name | lower }}
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/s/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: '{{ sha256 }}'

build:
  noarch: python
  entry_points:
    - schema-salad-tool=schema_salad.main:main
  number: 0

requirements:
  host:
    - python
    - setuptools
    - requests
    - rdflib ==4.2.2
    - rdflib-jsonld ==0.4
    - mistune ==0.7.3
    - typing ==3.6.4
    - ruamel.yaml >=0.12.4,<0.15.51
    - cachecontrol ==0.11.7
    - lockfile ==0.12.2
    - avro-python2 ==1.8.1
    - avro-cwl ==1.8.4
    - future
  run:
    - python
    - requests
    - rdflib ==4.2.2
    - rdflib-jsonld ==0.4
    - mistune ==0.7.3
    - typing >=3.6.4
    - ruamel.yaml >=0.12.4,<0.15.51
    - cachecontrol ==0.11.7
    - lockfile ==0.12.2
    - avro-python2 ==1.8.1
    - avro-cwl ==1.8.4
    - future

test:
  imports:
    - schema_salad
  commands:
    - schema-salad-tool --help

about:
  home: https://github.com/common-workflow-language/schema_salad
  license: Apache-2.0
  license_family: Apache
  summary: Schema Annotations for Linked Avro Data (SALAD)

extra:
  identifiers:
    - biotools:salad
