package:
  name: phizz
  version: "0.2.3"

source:
  url: https://files.pythonhosted.org/packages/e9/a9/ffdd3c5fa5418b93e29101dd4d2ac84f8143bdd0d34b897bd61b2b8b6208/phizz-0.0.1.tar.gz
  sha256: 4eab4e4f28396a50db1c97766acc9fc80c52d8d6ce89894f561c0c7a14a48e66

build:
  number: 0
  noarch: python
  preserve_egg_dir: true
  entry_points:
    - phizz = phizz.__main__:cli

requirements:
  host:
    - python
    - setuptools
    - click
    - configobj
    - intervaltree

  run:
    - python
    - setuptools
    - click
    - configobj
    - intervaltree

test:
  imports:
    - phizz
    - phizz.database
    - phizz.utils

  commands:
    - phizz --help

about:
  home: https://github.com/moonso/query_hpo
  license: MIT License
  summary: 'Tool to query hpo database and some other sources'

extra:
  container:
    # click requires a unicode locale when used with Python 3
    # extended-base generates en_US.UTF-8 locale and sets LC_ALL, LANG properly
    extended-base: true
