{% set version = "2.8.0" %}
{% set name = "pcaExplorer" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: b1c6b5b18d4ebf9cd7e1a5b7ec1eff1fe4b803917107ff43a6fcc0d17f6d463c
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-annotationdbi
    - bioconductor-biomart
    - bioconductor-deseq2
    - bioconductor-genefilter
    - bioconductor-genomicranges
    - bioconductor-go.db
    - bioconductor-gostats
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-topgo
    - r-base
    - r-d3heatmap
    - r-dt
    - 'r-ggplot2 >=2.0.0'
    - r-ggrepel
    - r-knitr
    - r-nmf
    - r-pheatmap
    - r-plyr
    - r-rmarkdown
    - r-scales
    - 'r-shiny >=0.12.0'
    - r-shinyace
    - r-shinybs
    - r-shinydashboard
    - r-threejs
    - r-tidyr
  run:
    - bioconductor-annotationdbi
    - bioconductor-biomart
    - bioconductor-deseq2
    - bioconductor-genefilter
    - bioconductor-genomicranges
    - bioconductor-go.db
    - bioconductor-gostats
    - bioconductor-iranges
    - bioconductor-limma
    - bioconductor-s4vectors
    - bioconductor-summarizedexperiment
    - bioconductor-topgo
    - r-base
    - r-d3heatmap
    - r-dt
    - 'r-ggplot2 >=2.0.0'
    - r-ggrepel
    - r-knitr
    - r-nmf
    - r-pheatmap
    - r-plyr
    - r-rmarkdown
    - r-scales
    - 'r-shiny >=0.12.0'
    - r-shinyace
    - r-shinybs
    - r-shinydashboard
    - r-threejs
    - r-tidyr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'MIT + file LICENSE'
  summary: 'This package provides functionality for interactive visualization of RNA-seq datasets based on Principal Components Analysis. The methods provided allow for quick information extraction and effective data exploration. A Shiny application encapsulates the whole analysis.'
extra:
  identifiers:
    - biotools:pcaexplorer
    - doi:10.18547/gcb.2017.vol3.iss1.e39
