{% set version = '2.5.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-speaq
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/speaq_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/speaq/speaq_{{ version }}.tar.gz
  sha256: c39e42a13dd2349a89b00f5153d22bb083a5cf470f3c650ca4e352d6fdd2c8e8

build:
  merge_build_host: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{posix}}zip               # [win]

  host:
    - r-base
    - bioconductor-massspecwavelet
    - r-cluster
    - r-data.table
    - r-dosnow
    - r-foreach
    - r-ggplot2
    - r-gridextra
    - bioconductor-impute
    - r-mqtl
    - r-missforest
    - r-reshape2
    - r-rvest
    - r-xml2

  run:
    - r-base
    - bioconductor-massspecwavelet
    - r-cluster
    - r-data.table
    - r-dosnow
    - r-foreach
    - r-ggplot2
    - r-gridextra
    - bioconductor-impute
    - r-mqtl
    - r-missforest
    - r-reshape2
    - r-rvest
    - r-xml2

test:
  commands:

    - $R -e "library('speaq')"           # [not win]
    - "\"%R%\" -e \"library('speaq')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=speaq
  license: Apache License 2.0
  summary: 'Makes Nuclear Magnetic Resonance spectroscopy (NMR spectroscopy) data analysis as
    easy as possible by only requiring a small set of functions to perform an entire
    analysis. ''speaq'' offers the possibility of raw spectra alignment and quantitation
    but also an analysis based on features whereby the spectra are converted to peaks
    which are then grouped and turned into features. These features can be processed
    with any number of statistical tools either included in ''speaq'' or available elsewhere
    on CRAN. More detail can be found in Vu et al. (2011) <doi:10.1186/1471-2105-12-405>
    and Beirnaert et al. (2018) <doi:10.1371/journal.pcbi.1006018>. '

  license_family: APACHE
extra:
  recipe-maintainers:
    - MathiasHaudgaard
    - FrodePedersen
    - ArneKr
    - johanneskoester
    - bgruening
    - daler
    - jdblischak
