{% set name = "rnalien" %}
{% set version = "1.5.0" %}
{% set sha256 = "ba43c4588f960eb371fa19cb7dfbbb2bce4f767a4c18043a8fb039e567d710bb" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://github.com/eggzilla/RNAlien/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True  #  [osx]

requirements:
  build:
    - stack >=1.9.3
    - gmp
    - zlib
    - perl

  run:
    - viennarna ==2.3.3
    - rnaz ==2.1
    - locarna ==1.9.1
    - infernal ==1.1.2
    - rnacode ==0.3
    - gmp
    - perl
    - zlib
    - openssl
    - ca-certificates

test:
  commands:
    - RNAlien --help

about:
  home: http://rna.tbi.univie.ac.at/rnalien/tool
  license: GPL-3
  summary: A tool for unsupervised construction of RNA family models

extra:
  identifiers:
    - biotools:RNAlien
    - doi:10.1093/nar/gkw558
