package:
  name: pybel
  version: "0.13.0"

source:
  url: https://files.pythonhosted.org/packages/87/08/244ab93a151ee532fb3fce07e0e830dd7237998cf030c588cb13b8e3e777/pybel-0.13.0.tar.gz
  sha256: 0f75a427dedc4d895f38f02dc779fc284f4f452372188250c79ec4633830b180

build:
  entry_points:
    - pybel = pybel.cli:main
  number: 0
  # tests fail on osx: https://travis-ci.org/bioconda/bioconda-recipes/jobs/235726973#L3656
  # click needs to be patched in order to properly detect unicode in py3k
  skip: true  # [osx or py3k]

requirements:
  host:
    - python
    - setuptools
    - requests
    - ndex-python
    - requests-file
    - networkx
    - pyparsing
    - configparser  # [py27]
    - py2neo
    - click
    - sqlalchemy
    - onto2nx
  run:
    - python
    - requests
    - ndex-python
    - requests-file
    - networkx
    - pyparsing
    - configparser  # [py27]
    - py2neo
    - click
    - sqlalchemy
    - onto2nx

test:
  # Python imports
  imports:
    - pybel
    - pybel.ext
    - pybel.manager
    - pybel.parser
    - pybel.parser.modifiers
  commands:
    # click requires a unicode locale
    - LANG=C.UTF-8 pybel --help

about:
  home: https://github.com/pybel/pybel
  license: Apache Software License
  summary: 'PyBEL is a Python package for parsing and handling biological networks encoded in the Biological Expression Language (BEL)'
