package:
  name: mendelscan
  version: "1.2.2"

source:
  url: https://github.com/genome/mendelscan/releases/download/1.2.2/MendelScan.v1.2.2.jar
  sha256: 48d4186e39072429ffe33c3101a23b26a0da2f80fac107ceeeb3d4748485a3d4

build:
  detect_binary_files_with_prefix: True
  number: 0
  skip: False

requirements:
  run:
    - java-jdk

test:
  commands:
    - mendelscan -h 2>&1 | grep USAGE > /dev/null

about:
  home: https://github.com/genome/mendelscan
  license: Unknown
  summary: 'Analyze exome data for Mendelian disorders.'
