package:
  name: mzml2isa
  version: "1.0.1"

source:
  url: https://files.pythonhosted.org/packages/30/af/976ff0c712fe97affb9b84d29acc0524976c2059df1b1bc01f9814108ffb/mzml2isa-1.0.1.zip
  sha256: 610b2f91afaaa6e986ad516be09929402e73c34400ae420d4e18f5e629964079

build:
  noarch: python
  number: 0
  entry_points:
    - mzml2isa = mzml2isa.parsing:main

requirements:
  host:
    - python
    - setuptools
    - six
    - pronto >=0.6.0
    - openpyxl

  run:
    - python
    - six
    - pronto >=0.6.0
    - openpyxl

test:
  imports:
    - mzml2isa

  commands:
    - mzml2isa --help

about:
  home: https://github.com/ISA-tools/mzml2isa
  license: GNU General Public License v3 (GPLv3)
  summary: 'mzml2isa - mzML to ISA-tab parsing tool'
  license_family: GPL3

