{% set version = "4.0.1" %}

package:
  name: rmats
  version: {{ version }}

source:
  fn: rMATS.{{ version }}.tgz
  sha256: 67f58f572b2832e77525f413cd91b23818a67b11f89d5499a7e89764908d6498
  url: https://sourceforge.net/projects/rnaseq-mats/files/MATS/rMATS.{{ version }}.tgz

build:
  number: 0
  skip: True    # [py3k or osx]

requirements:
  host:
    - python
    - numpy
    - scipy

  run:
    - python
    - numpy
    - scipy
    - star >=2.5

test:
  commands:
    - rmats.py

about:
  home: http://rnaseq-mats.sourceforge.net
  license: MIT
  summary: MATS is a computational tool to detect differential alternative splicing events from RNA-Seq data.
