{% set version = "2.9.6" %}
{% set sha256 = "4be42f4d62b2376dc2fc4cd992822525bd99f8e1193008c2dab387a2f291405b" %}

package:
  name: ncbi-ngs-sdk
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/ncbi/ngs/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl
    - libiconv
    - libxml2

about:
  home: https://github.com/ncbi/ngs
  license: Public Domain
  summary: NGS is a new, domain-specific API for accessing reads, alignments and pileups produced from Next Generation Sequencing.

test:
  commands:
    - test -e ${PREFIX}/lib64/libngs-sdk.so # [not osx]
    - test -e ${PREFIX}/lib64/libngs-sdk.dylib # [osx]

