package:
  name: zeroc-ice
  version: '3.7.2'

source:
  url: https://files.pythonhosted.org/packages/47/4a/583e21a207e0675f618363e3d5a123d7b40d859e20ac4913d8f2ec6ec6d6/zeroc-ice-3.7.2.tar.gz
  sha256: a846798351075db4d4d52f741157a79a1d40d27fe8beaf84a62f349be68047af

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - setuptools
    - bzip2

  run:
    - python
    - bzip2

test:
  imports:
    - Ice

about:
  home: https://github.com/zeroc-ice
  license: GPL v2 with exceptions
  summary: Ice is a comprehensive RPC framework that helps you network your software with minimal effort.
