{% set name = "maxbin2" %}
{% set version = "2.2.5" %}
{% set md5 = "cb0a3dd1544159056326fa76b5b01f36" %}

build:
  number: 1

package:
  name: {{ name }}
  version: {{ version }}
source:
  url: http://downloads.jbei.org/data/microbial_communities/MaxBin/getfile.php?MaxBin-{{ version }}.tar.gz
  md5: {{ md5 }}
  patches:
    - makefile.patch
requirements:
  build:
    - {{ compiler('c') }}
  run:
    - fraggenescan >=1.30
    - bowtie2
    - hmmer
    - idba
    - perl-lwp-simple
    - r-base
    - r-gplots
test:
  commands:
    - run_MaxBin.pl

about:
  home: "http://downloads.jbei.org/data/microbial_communities/MaxBin/MaxBin.html"
  license: "BSD 3-clause"
  summary: "MaxBin is software for binning assembled metagenomic sequences based on an Expectation-Maximization algorithm."

extra:
  recipe-maintainers:
    - colinbrislawn
    - keuv-grvl
    - ursky
  doi:
    - 10.1186/2049-2618-2-26
    - 10.1093/bioinformatics/btv638
