package:
  name: calib
  version: "0.2"

source:
  url: https://github.com/vpc-ccg/calib/archive/v{{ PKG_VERSION }}.tar.gz
  sha256: 793e3b2fa6eadad683f3d10cfc060591e41325ca734ce90c89bbeb94f97aa470

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}

test:
  commands:
    - calib -h
    - calib_cons -h

about:
  home: https://github.com/vpc-ccg/calib
  license: MIT
  summary: Calib clusters barcode tagged paired-end reads based on their barcode and sequence similarity.

