{% set version = "0.929" %}
{% set sha256 = "770d6345e326f35ec02c1b803d2461be9e23280c05bda00dd5e09245b012bd9b" %}

package:
  name: angsd
  version: {{ version }}

source:
  url: https://github.com/ANGSD/angsd/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
  host:
    - htslib
  run:
    - htslib

test:
  commands:
    - angsd 2>&1 | grep "angsd version"
    - thetaStat 2>&1 | grep "neutrality test"

about:
  home: http://www.popgen.dk/angsd/index.php/ANGSD
  license: GPLv3, MIT
  summary: "ANGSD: Analysis of next generation Sequencing Data"

extra:
  identifiers:
    - biotools:angsd
    - doi:10.1186/s12859-014-0356-4
