{% set version = '0.5.1' %}

package:
  name: r-mdmr
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/MDMR_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/MDMR/MDMR_{{ version }}.tar.gz
  sha256: 5d18c3379ca6e7762f218c2c9fc8c9b49aa194acce5624c3ef58cb7b683f65df

build:
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: knitr, rmarkdown
requirements:
  build:
    number: 0

  host:
    - r-base
    - r-compquadform
    - r-car
    - r-lme4

  run:
    - r-base
    - r-compquadform
    - r-car
    - r-lme4

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('MDMR')"

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://github.com/dmcartor/mdmr
  license: GPL (>= 2)
  summary: Allows users to conduct multivariate distance matrix regression using analytic p-values
    and compute measures of effect size. For details on the method, see McArtor, Lubke,
    & Bergeman (2017) <doi:10.1007/s11336-016-9527-8>.
  license_family: GPL3
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-2'

# The original CRAN metadata for this package was:

# Package: MDMR
# Type: Package
# Title: Multivariate Distance Matrix Regression
# Version: 0.5.1
# Date: 2018-02-11
# Author: Daniel B. McArtor (dmcartor@gmail.com) [aut, cre]
# Maintainer: Daniel B. McArtor <dmcartor@gmail.com>
# Description: Allows users to conduct multivariate distance matrix regression using analytic p-values and compute measures of effect size. For details on the method, see McArtor, Lubke, & Bergeman (2017) <doi:10.1007/s11336-016-9527-8>.
# License: GPL (>= 2)
# LazyData: TRUE
# Depends: R (>= 3.0.0),
# Imports: CompQuadForm, parallel, lme4, car
# Suggests: knitr, rmarkdown
# VignetteBuilder: knitr
# URL: http://github.com/dmcartor/mdmr
# BugReports: http://github.com/dmcartor/mdmr/issues
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2018-02-14 03:41:15 UTC; Dan
# Repository: CRAN
# Date/Publication: 2018-02-14 18:16:13 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
