{% set name = "hic2cool" %}
{% set version = "0.7.2" %}
{% set sha256 = "c89c5e865ec793d98b054480da6269eb59e0557e7a84ef49962037388ae9c5ef" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/4dn-dcic/hic2cool/archive/{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - setuptools
    - numpy >=1.16.3
    - scipy >=1.2.1
    - cooler >=0.8.5
    - h5py >=2.8.0
  run:
    - python
    - numpy >=1.16.3
    - scipy >=1.2.1
    - cooler >=0.8.5
    - h5py >=2.8.0

test:
  imports:
    - hic2cool
  commands:
    - hic2cool --version

about:
  home: https://github.com/4dn-dcic/hic2cool
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: "A converter between .hic files (from juicer) and .cool files (for cooler)."
