{% set name = "sonicparanoid" %}
{% set version = "1.1.0" %}
{% set commit = "43a67d7b5cf1" %}

build:
  number: 0

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://bitbucket.org/salvocos/sonicparanoid/get/{{ commit }}.zip
  sha256: e53b263ef56228d710b3b864a81d704198dd9e98fb77a9d8f5e0f457e13b6f2d

requirements:
  build:
    - {{ compiler("c") }}
  host:
    - make
    - python >=3.5
    - numpy
    - cython
    - mmseqs2 ==6.f5a1c
  run:
    - mmseqs2 ==6.f5a1c
    - make
    - python >=3.5
    - pip >=9.0.1
    - cython >=0.27.0
    - setuptools >=24.2.0
    - biopython >=1.67
    - pandas >=0.22.0
    - numpy >=1.13.0
    - sh >=1.12.14

test:
  commands:
    - "sonicparanoid"
    - "sonicparanoid-get-test-data --help"

about:
  home: "http://iwasakilab.bs.s.u-tokyo.ac.jp/sonicparanoid/"
  license: "GNU General Public License v3"
  license_family: "GPL3"
  license_file: "LICENSE.md"
  summary: "SonicParanoid: fast, easy and accurate orthology inference"

extra:
  identifiers:
    - https://doi.org/10.1093/bioinformatics/bty631
