{% set name = "sonicparanoid" %}
{% set version = "1.1.0" %}
{% set commit = "cabe9c8bc538" %}


build:
  number: 0

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://bitbucket.org/salvocos/sonicparanoid/get/{{ commit }}.zip
  sha256: 68ae3060556ea46acaf88ae20da016dce5d6a03d3257df707e2d4c0fd2cc5bc9

requirements:
  build:
    - {{ compiler("c") }}
    - numpy >=1.14.0
  host:
    - make
    - python >=3.5
    - scipy >=1.1.0
    - numpy >=1.14.0
    - cython
    - mmseqs2 ==6.f5a1c
  run:
    - mmseqs2 ==6.f5a1c
    - make
    - python >=3.5
    - pip >=9.0.1
    - cython >=0.27.0
    - setuptools >=24.2.0
    - biopython >=1.67
    - pandas >=0.22.0
    - scipy >=1.1.0
    - numpy >=1.14.0
    - sh >=1.12.14

test:
  commands:
    - "sonicparanoid --help"
    - "sonicparanoid-get-test-data --help"

about:
  home: "http://iwasakilab.bs.s.u-tokyo.ac.jp/sonicparanoid/"
  license: "GNU General Public License v3"
  license_family: "GPL3"
  license_file: "LICENSE.md"
  summary: "SonicParanoid: fast, easy and accurate orthology inference"

extra:
  identifiers:
    - https://doi.org/10.1093/bioinformatics/bty631
