{% set version = "0.3.2" %}

package:
  name: downpore
  version: {{ version }}

source:
  url: https://github.com/jteutenberg/downpore/archive/{{ version }}.tar.gz
  sha256: 944d5dd5f58fe6f93ec3493b01f71efc0416738a6e975f31b49ef1eba9709f2b

build:
  number: 0

requirements:
  build:
    - go
  run:

test:
  commands:
    - downpore

about:
  home: https://github.com/jteutenberg/downpore
  license: MIT
  license_file: LICENSE
  summary: Suite of tools for use in genome assembly and consensus.
