{% set version = "0.5.6" %}
{% set sha256 = "57eeab0ed2f408126318533150e4b70028c6e6787c483ba4ed29f1433c6e6e0a" %}

package:
  name: krakenuniq
  version: {{ version }}

source:
  url: https://github.com/fbreitwieser/krakenuniq/archive/v{{ version }}.tar.gz
  sha256: {{ sha256 }}
  patches:
    - Makefile.patch

build:
  number: 2
  has_prefix_files:
    - libexec/krakenuniq
    - libexec/krakenuniq-build
    - libexec/krakenuniq-download

requirements:
  build:
    - {{ compiler('cxx') }}

  host:
    - perl
    - zlib
    - clangdev  # [osx]
    - libcxx 4.0.*  # [osx]
    - openmp 4.0.*  # [osx]
  run:
    - perl
    - zlib
    - libcxx >=4.0  # [osx]
    - openmp >=4.0  # [osx]
    - jellyfish 1.*
    - perl-libwww-perl
    - perl-lwp-protocol-https

test:
  commands:
    - krakenuniq --version
    - krakenuniq-build --version
    - krakenuniq-extract-reads --help 2>&1 | grep Usage
    - krakenuniq-filter --version
    - krakenuniq-mpa-report --version
    - krakenuniq-report --version
    - krakenuniq-translate --version

about:
  home: https://github.com/fbreitwieser/krakenuniq
  license: GPLv3
  license_file: LICENSE
  summary: Fast and precise metagenomics classification engine

extra:
  identifiers:
    - biotools:krakenuniq
    - doi:10.1186/s13059-018-1568-0
