{% set version="1.9.1" %}

package:
  name: synapseclient
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/s/synapseclient/synapseclient-{{ version }}.tar.gz
  sha256: a08094216cb6655cea631d4744abd0e8a2ae50131f230898cf3061ef8c2cca4c

build:
  noarch: python
  skip: False
  entry_points:
    - synapse = synapseclient.__main__:main
  number: 0

requirements:
  host:
    - python
    - setuptools
    - requests >=1.2
    - six
    - future
    - backports.csv

  run:
    - python
    - requests >=1.2
    - six
    - future
    - backports.csv

test:
  imports:
    - synapseclient
  commands:
    - synapse --help
  requires:
    - mock
    - nose

about:
  home: http://synapse.sagebase.org/
  license: Apache Software License
  summary: 'A client for Synapse, a collaborative compute space  that allows scientists to share and analyze data together.'
