{% set version = "1.0.15" %}
{% set build = "5" %}
package:
  name: strelka1
  version: {{ version }}

source:
  url: ftp://strelka:%27%27@ftp.illumina.com/v1-branch/v1.0.15/strelka_workflow-1.0.15.tar.gz
  sha256: e2661cc6066b34615ba82fe84315702a88b47d7474ed28c049603648b9688ab3

build:
  number: {{ build }}

requirements:
  build:
    - make
    - zlib
  run:
    - perl

test:
  commands:
    - bash $PREFIX/bin/strelka1-src/bin/demo/run_demo.bash

about:
  home: https://sites.google.com/site/strelkasomaticvariantcaller/home
  summary: Somatic variant calling workflow for matched tumor-normal samples
  license: GPL-3.0
  license_family: GPL
