{% set version = "1.0.15" %}
{% set build = "5" %}
package:
  name: strelka1
  version: {{ version }}

source:
  url: https://anaconda.org/matnguyen/strelka1/1.0.15/download/linux-64/strelka1-{{ version }}-{{ build }}.tar.bz2
  sha256: 6abb6027b24fcc80473e223f660467a5be6b800b35a788725d6f8d6250acc2c0

build:
  number: {{ build }}

requirements:
  build:
    - make
    - zlib
  run:
    - perl

test:
  commands:
    - bash $PREFIX/bin/strelka1-src/bin/demo/run_demo.bash

about:
  home: https://sites.google.com/site/strelkasomaticvariantcaller/home
  summary: Somatic variant calling workflow for matched tumor-normal samples
  license: GPL-3.0
  license_family: GPL
