{% set version = "0.14.1" %}

package:
  name: cobra
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/33/45/eedd5a1e936530d72f68d518b1f162fcf91f219561b44be552f0bf3b0899/cobra-{{ version }}.tar.gz
  sha256: feaf15d16638f12fbf1a854b3623c215c996e73246f67753c4123f8d39ae6120

build:
  noarch: python
  number: 0

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - six
    - future
    - swiglpk
    - ruamel.yaml <0.15
    - numpy >=1.6
    - pandas >=0.17.0
    - optlang >=1.2.5
    - tabulate

test:
  imports:
    - cobra
    - cobra.core
    - cobra.flux_analysis
    - cobra.io
    - cobra.manipulation
    - cobra.test
    - cobra.util

about:
  home: https://opencobra.github.io/cobrapy
  license: GNU Lesser General Public License v2 or later (LGPLv2+) or GNU General Public License v2 or later (GPLv2+)
  summary: 'COBRApy is a package for constraint-based modeling of biological networks'
