#
# Notes:
# 
#   1. The conda-forge version of ncurses may be required to run properly
#   2. For some terminals (e.g. termite), the environmental variable "TERMINFO" may
#      need to be explicitly set, e.g. 'export TERMINFO=/usr/share/terminfo'
#
package:
  name: tabview
  version: "1.4.3"

source:
  url: https://files.pythonhosted.org/packages/84/10/3ba8c474cfda857cb01b1e28b38de86dec2f35fa434cc0315727fb290f79/tabview-1.4.3.tar.gz
  md5: 1c6a343fc470f513d9e6deda5f4ae965

build:
  noarch: python
  number: 0
  skip: False

requirements:
  host:
    - python
    - setuptools
    - ncurses

  run:
    - python
    - ncurses

test:
  imports:
    - tabview

  commands:
    - tabview -h > /dev/null || [[ "$?" == 2 ]]

about:
  home: https://github.com/firecat53/tabview
  license: MIT License
  summary: 'A curses command-line CSV and list (tabular data) viewer'
