{% set name = "corset" %}
{% set version = "1.08" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

build:
  number: 0

source:
  url: https://github.com/Oshlack/Corset/archive/version-1.08.tar.gz
  sha256: 5f9eb5847d02dd45369676925d067ee58285d37ec013b651825e7b482b217c06

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - zlib
    - samtools 0.1.19
  run:

test:
  commands:
    - corset 2>&1 | grep Usage

about:
  home: https://github.com/Oshlack/Corset
  license: GPLv3
  summary: 'Software for clustering de novo assembled transcripts and counting overlapping reads.'

extra:
  identifiers:
    - biotools:corset
    - doi:10.1186/s13059-014-0410-6
