package:
  name: perl-xml-libxml
  version: "2.0200"

source:
  url: https://cpan.metacpan.org/authors/id/S/SH/SHLOMIF/XML-LibXML-2.0200.tar.gz
  sha256: 8248bdd72850391b065c67937882cfbd224542979c4c2f0d4804add3ed376e83

build:
  number: 0

requirements:
  host:
    - perl
    - perl-xml-sax
    - perl-xml-namespacesupport
    - libxml2
  run:
    - perl
    - perl-xml-sax
    - perl-xml-namespacesupport
    - libxml2

test:
  # Perl 'use' tests
  imports:
    - XML::LibXML
    - XML::LibXML::AttributeHash
    - XML::LibXML::Boolean
    - XML::LibXML::Common
    - XML::LibXML::Devel
    - XML::LibXML::ErrNo
    - XML::LibXML::Error
    - XML::LibXML::Literal
    - XML::LibXML::NodeList
    - XML::LibXML::Number
    - XML::LibXML::Reader
    - XML::LibXML::SAX
    - XML::LibXML::SAX::Builder
    - XML::LibXML::SAX::Generator
    - XML::LibXML::SAX::Parser
    - XML::LibXML::XPathContext

about:
  home: https://bitbucket.org/shlomif/perl-xml-libxml
  license: Perl
  summary: 'Interface to Gnome libxml2 xml parsing and DOM library'
