{% set name = "maxbin2-full" %}
{% set version = "2.2.5" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://bitbucket.org/berkeleylab/metabat/downloads/metabat-static-binary-linux-x64_v2.12.1.tar.gz
  md5: cb0a3dd1544159056326fa76b5b01f36

build:
  number: 1
  skip: True # [osx]

requirements:
  build: 
    - gcc >=4
    - perl >=5

  run:
    - bowtie2 >=2
    - fraggenescan >=1.3
    - hmmer 3.1b2
    - idba 1.1.3

test:
  commands:
    - run_MaxBin.pl

about:
  home: https://downloads.jbei.org/data/microbial_communities/MaxBin/MaxBin.html
  license: BSD
  license_file: LICENSE
  summary: "MaxBin2 is a program for binning metagenome-assembled contigs into bins/MAGs."


