build:
  number: 0
  skip: True # [osx]

package:
  name: argutils
  version: "0.3.3"

source:
  url: https://files.pythonhosted.org/packages/8e/7f/51286ee6cb8e1c223aa05c2a686f8ef00139bf91969f3109ec8c0d84e67d/argutils-0.3.3.tar.gz
  sha256: 3152e6e602847bbcc8868b3adc1284d6008c3dda4bb9b366d7c60778a2538894

requirements:
  host:
    - python
    - setuptools
    - six
    - pyyaml
  run:
    - python
    - six
    - pyyaml

test:
  imports:
    - argutils

about:
  home: https://github.com/eclarke/argutils
  license: GNU General Public License v2 or later (GPLv2+)
  summary: 'Functions to build matched argument parsers and config files'
