# Migrated from https://anaconda.org/quanyuan/gcs-oauth2-boto-plugin

package:
  name: gcs-oauth2-boto-plugin
  version: "2.3"

source:
  url: https://files.pythonhosted.org/packages/53/ef/ac13239328b5d0727079b5298265f7fec272d4fe2ee0c145d341944611f8/gcs-oauth2-boto-plugin-2.3.tar.gz
  sha256: b4711cde779bbb057c8dc104e64c98c25559e23a14b3a201e36f514828f6d0ec

build:
  number: 0
  skip: True # [not py27]

requirements:
  host:
    - cryptography
    - python
    - setuptools
    - boto >=2.29.1
    - httplib2 >=0.8
    - google-api-python-client >=1.1
    - pyopenssl >=0.13
    - socksipy-branch ==1.01
    - retry_decorator >=1.0.0

  run:
    - python
    - boto >=2.29.1
    - httplib2 >=0.8
    - google-api-python-client >=1.1
    - pyopenssl >=0.13
    - socksipy-branch ==1.01
    - retry_decorator >=1.0.0

test:
  imports:
    - gcs_oauth2_boto_plugin

about:
  home: https://developers.google.com/storage/docs/gspythonlibrary
  license: Apache 2.0
  summary: 'Auth plugin allowing use the use of OAuth 2.0 credentials for Google Cloud Storage in the Boto library.'
