# Migrated from https://anaconda.org/quanyuan/gcs-oauth2-boto-plugin

package:
  name: gcs-oauth2-boto-plugin
  version: "2.4"

source:
  url: https://files.pythonhosted.org/packages/79/e4/032190c0b1e2330e50f2f87962cf9c9823312607f2c9a11974e2cff2ec80/gcs-oauth2-boto-plugin-2.4.tar.gz
  sha256: 7c2f77dab8ca01c8956782fc6cd6be516517ed0d89e53dfa7a0e97a70b2e4b61

build:
  number: 0
  skip: True # [not py27]

requirements:
  host:
    - cryptography
    - python
    - setuptools
    - boto >=2.29.1
    - httplib2 >=0.8
    - google-api-python-client >=1.1
    - pyopenssl >=0.13
    - socksipy-branch ==1.01
    - retry_decorator >=1.0.0

  run:
    - python
    - boto >=2.29.1
    - httplib2 >=0.8
    - google-api-python-client >=1.1
    - pyopenssl >=0.13
    - socksipy-branch ==1.01
    - retry_decorator >=1.0.0

test:
  imports:
    - gcs_oauth2_boto_plugin

about:
  home: https://developers.google.com/storage/docs/gspythonlibrary
  license: Apache 2.0
  summary: 'Auth plugin allowing use the use of OAuth 2.0 credentials for Google Cloud Storage in the Boto library.'
