{% set version = "1.8.1" %}

package:
  name: mpa-portable
  version: {{ version }}

build:
  number: 0
  skip: True  # [osx]

source:
  url: https://github.com/compomics/meta-proteome-analyzer/releases/download/v{{ version }}/mpa-portable-{{ version }}.zip
  sha256: cca6ce2eddd52287894bb161e8dc07bf2f5e1d2918523c418a4365503b38fd72

requirements:
  run:
    - openjdk >=6
    - python

test:
  commands:
    - mpa-portable de.mpa.cli.CmdLineInterface -Djava.awt.headless=true -Xmx2048m 2>&1
    - mpa-portable de.mpa.cli.CmdLineInterface -Djava.awt.headless=true -Xmx2048m 2>&1 | grep MPA

about:
  home: https://github.com/compomics/meta-proteome-analyzer
  license: Apache License, Version 2.0
  summary: |
    MPA Portable is a light-weight and stand-alone software for the
    identification of proteins and in-depth analysis of metaproteomics.

extra:
  notes: |
    mpa-protable is Java program that comes with a custom wrapper shell script.
