{% set version = "2.6.4" %}
{% set name = "MSnbase" %}
{% set bioc = "3.6" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://bioconductor.org/packages/release/bioc/src/contrib/MSnbase_2.6.4.tar.gz
  sha256: 35872e6a5057deb33ff46bb544c0c15c781f6ae15f3551b437b6b41c166a3bb2
  
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - bioconductor-affy
    - 'bioconductor-biobase >=2.15.2'
    - 'bioconductor-biocgenerics >=0.7.1'
    - bioconductor-biocparallel
    - bioconductor-impute
    - bioconductor-iranges
    - 'bioconductor-mzid >=1.5.2'
    - 'bioconductor-mzr >=2.11.11'
    - bioconductor-pcamethods
    - bioconductor-preprocesscore
    - 'bioconductor-protgenerics >=1.9.1'
    - bioconductor-s4vectors
    - bioconductor-vsn
    - r-base
    - r-digest
    - r-ggplot2
    - r-lattice
    - 'r-maldiquant >=1.16'
    - r-plyr
    - r-rcpp
    - r-xml
  run:
    - bioconductor-affy
    - 'bioconductor-biobase >=2.15.2'
    - 'bioconductor-biocgenerics >=0.7.1'
    - bioconductor-biocparallel
    - bioconductor-impute
    - bioconductor-iranges
    - 'bioconductor-mzid >=1.5.2'
    - 'bioconductor-mzr >=2.11.11'
    - bioconductor-pcamethods
    - bioconductor-preprocesscore
    - 'bioconductor-protgenerics >=1.9.1'
    - bioconductor-s4vectors
    - bioconductor-vsn
    - r-base
    - r-digest
    - r-ggplot2
    - r-lattice
    - 'r-maldiquant >=1.16'
    - r-plyr
    - r-rcpp
    - r-xml

test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'MSnbase provides infrastructure to manipulation, processing and visualisation mass spectrometry and proteomics data, ranging from raw to quantitative and annotated data.'

extra:
  identifiers:
    - biotools:msnbase
