{% set version = "1.0.0" %}
{% set name = "RNASeqR" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'http://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name|lower }}/bioconductor-{{ name|lower }}_{{ version }}_src_all.tar.gz'
  sha256: 4b1bb7a4c704d058363f6d81556ffda9778b18655069a9f4d47b7cd38db5a7bb
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
requirements:
  host:
    - bioconductor-ballgown
    - bioconductor-biostrings
    - bioconductor-clusterprofiler
    - bioconductor-deseq2
    - bioconductor-dose
    - bioconductor-edger
    - bioconductor-org.hs.eg.db
    - bioconductor-org.sc.sgd.db
    - bioconductor-pathview
    - bioconductor-rsamtools
    - bioconductor-systempiper
    - bioconductor-systempiperdata
    - r-base
    - r-corrplot
    - r-factoextra
    - r-factominer
    - r-ggplot2
    - r-gridextra
    - r-performanceanalytics
    - r-pheatmap
    - r-rafalib
    - r-reshape2
    - r-reticulate
    - r-stringr
  run:
    - bioconductor-ballgown
    - bioconductor-biostrings
    - bioconductor-clusterprofiler
    - bioconductor-deseq2
    - bioconductor-dose
    - bioconductor-edger
    - bioconductor-org.hs.eg.db
    - bioconductor-org.sc.sgd.db
    - bioconductor-pathview
    - bioconductor-rsamtools
    - bioconductor-systempiper
    - bioconductor-systempiperdata
    - r-base
    - r-corrplot
    - r-factoextra
    - r-factominer
    - r-ggplot2
    - r-gridextra
    - r-performanceanalytics
    - r-pheatmap
    - r-rafalib
    - r-reshape2
    - r-reticulate
    - r-stringr
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'http://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: Artistic-2.0
  summary: 'This R package is designed for case-control RNA-Seq analysis (two-group). There are six steps: "RNASeqRParam S4 Object Creation", "Environment Setup", "Quality Assessment", "Reads Alignment & Quantification", "Gene-level Differential Analyses" and "Functional Analyses". Each step corresponds to a function in this package. After running functions in order, a basic RNASeq analysis would be done easily.'
