{% set version = "1.9.5" %}

package:
  name: lambda
  version: {{ version }}

source:
  url: https://github.com/seqan/lambda/archive/lambda-v{{ version }}.tar.gz
  sha256: eb891eac2ec4eedbf96828c58a691570ee17f23566fdc2f212f81305cf699d10

build:
  number: 0
  skip: True # [osx]

requirements:
  build:
    - gxx_linux-64 # [linux]
    - cmake >=3.0.0
    - seqan-library
  host:
    - openmp
    - bzip2
    - zlib

test:
  commands:
    - lambda --help


about:
  home: http://seqan.github.io/lambda/
  license: AGPLv3
  summary: Lambda is a local aligner optimized for many query sequences and searches in protein space
