package:
  name: presto
  version: "0.5.11"

source:
  url: https://files.pythonhosted.org/packages/6e/55/1b468434ba1185f44fc9f7b3714be090cda12e95d809a4d4d9f1dee6d616/presto-0.5.11.tar.gz
  sha256: 1fd6ef06ec1fe02aec87fecf3ed7bbff39596dab8d55eb0df3c9525921cad80b

build:
  number: 0
  # Presto only supports python3
  skip: True # [not py3k]


requirements:
  host:
    - python
    - setuptools
    - numpy >=1.8
    - scipy >=0.14
    - pandas >=0.15
    - biopython >=1.65

  run:
    - python
    - numpy >=1.8
    - scipy >=0.14
    - pandas >=0.15
    - biopython >=1.65
    - blast >=2.5
    - muscle >=3.8
    - vsearch >=2.3.2

test:
  commands:
    - AlignSets.py --version
    - AssemblePairs.py --version
    - BuildConsensus.py --version
    - ClusterSets.py --version
    - CollapseSeq.py --version
    - ConvertHeaders.py --version
    - EstimateError.py --version
    - FilterSeq.py --version
    - MaskPrimers.py --version
    - PairSeq.py --version
    - ParseHeaders.py --version
    - ParseLog.py --version
    - SplitSeq.py --version

about:
  home: http://presto.readthedocs.io
  license: Creative Commons Attribution-ShareAlike 4.0 International (CC BY-SA 4.0)
  summary: 'A bioinformatics toolkit for processing high-throughput lymphocyte receptor sequencing data.'
  license_family: OTHER
