package:
  name: elasticluster
  version: '1.1.1'

source:
  #url: https://github.com/jwm/elasticluster/archive/abf3ab1.tar.gz
  url: https://github.com/chapmanb/elasticluster/archive/1.1.1.tar.gz
  sha256: 174d0ca8e7701b2c7660b64a0438afdc27b21815910a406fdc3789a855882b74

build:
  number: 0
  skip: True # [not py27]

requirements:
  host:
    - python
    - setuptools

  run:
    - python
    - ansible
    - azure
    - pycli
    - paramiko
    - voluptuous
    - configobj
    - boto
    - google-api-python-client
    - oauth2client
    - python-gflags

test:
  # Python imports
  imports:
    - elasticluster
    - elasticluster.conf
    - elasticluster.main
    - elasticluster.providers.ansible_provider
    - elasticluster.providers.ec2_boto

about:
  home: https://github.com/gc3-uzh-ch/elasticluster
  license: GPL
  summary: Create, manage and setup computing clusters hosted on a public or private cloud infrastructure.
