{% set name = "pyprophet" %}
{% set version = "2.0.3" %}
{% set hash_type = "sha256" %}
{% set hash_value = "b81e68d33125b4f0b06e392cdd75ae350e4fbce9b6a452eba5002eb4886d15f1" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  skip: True  # [not py27]
  entry_points:
    - pyprophet=pyprophet.main:main
  script: python -m pip install --no-deps --ignore-installed .

requirements:
  host:
    - python
    - pip
    - setuptools
    - numpy >=1.9.0
    - pandas >=0.17
    - scipy >=0.9.0
    - numexpr >=2.1
    - scikit-learn >=0.17
    - matplotlib
    - seaborn
  run:
    - python
    - numpy >=1.9.0
    - pandas >=0.17
    - scipy >=0.9.0
    - numexpr >=2.1
    - scikit-learn >=0.17
    - matplotlib
    - seaborn

test:
  imports:
    - pyprophet
  commands:
    - pyprophet --help

about:
  home: http://github.com/uweschmitt/pyprophet
  license: BSD License
  license_family: BSD
  summary: Python reimplementation of mProphet peak scoring
